version: "3.7"

services:
  wordpress:
    image: verzola/dockerpress
    environment:
      - WP_DB_HOST=${WP_DB_HOST:-mysql}
      - WP_DB_NAME=${WP_DB_NAME:-dockerpress}
      - WP_TABLE_PREFIX=${WP_TABLE_PREFIX:-wp_}
      - WP_DB_USER=${WP_DB_USER:-dockerpress}
      - WP_DB_PASSWORD=${WP_DB_PASSWORD:-changeme}
      - WP_AUTH_KEY=${WP_AUTH_KEY:-dev}
      - WP_SECURE_AUTH_KEY=${WP_SECURE_AUTH_KEY:-dev}
      - WP_LOGGED_IN_KEY=${WP_LOGGED_IN_KEY:-dev}
      - WP_NONCE_KEY=${WP_NONCE_KEY:-dev}
      - WP_AUTH_SALT=${WP_AUTH_SALT:-dev}
      - WP_SECURE_AUTH_SALT=${WP_SECURE_AUTH_SALT:-dev}
      - WP_LOGGED_IN_SALT=${WP_LOGGED_IN_SALT:-dev}
      - WP_NONCE_SALT=${WP_NONCE_SALT:-dev}
      - WP_DEBUG=${WP_DEBUG:-1}
      - MAIL_HOST=${MAIL_HOST:-mailhog}
      - MAIL_PORT=${MAIL_PORT:-1025}
      - MAIL_USERNAME=${MAIL_USERNAME:-null}
      - MAIL_PASSWORD=${MAIL_PASSWORD:-null}
      - MAIL_ENCRYPTION=${MAIL_ENCRYPTION:-null}
    volumes:
      - ./app/:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:${MYSQL_VERSION:-8.0}
    ports:
      - 3306:3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_USER=${MYSQL_USER:-dockerpress}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-changeme}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-dockerpress}
    volumes:
      - database-volume:/var/lib/mysql
    command: "--default-authentication-plugin=mysql_native_password"

  nginx:
    image: nginx:${NGINX_VERSION:-1.21-alpine}
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
      - ./data/nginx:/etc/nginx/conf.d
    depends_on:
      - wordpress

volumes:
  database-volume:
