version: '3'

services:

  wordpress:
    image: wordpress:5.0.0-apache
    env_file: .env
    ports:
      - 80:80
    volumes:
      - ./app/themes:/var/www/html/wp-content/themes
      - ./app/mu-plugins:/var/www/html/wp-content/mu-plugins
      - ./app/plugins:/var/www/html/wp-content/plugins
      - ./app/uploads:/var/www/html/wp-content/uploads
      - ./app/wp-config.php:/var/www/html/wp-config.php

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wordpress
    volumes:
      - ./database/mysql:/var/lib/mysql

  dev:
    image: node:11
    command: ./dev
    volumes:
      - ./app/themes/base/:/app/
    working_dir: /app
    ports:
      - 3000:3000
      - 3001:3001
