version: '3'

services:

  wordpress:
    image: wordpress:5-apache
    env_file: .env
    ports:
      - 80:80
    volumes:
      - ./app/:/var/www/html

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wordpress
    volumes:
      - ./database/mysql:/var/lib/mysql

  dev:
    image: node:11
    command: ./dev
    volumes:
      - ./app/themes/base/:/app/
    working_dir: /app
    ports:
      - 3000:3000
      - 3001:3001
    tty: true
    environment:
      - TERM=xterm-256color
