version: '3'

services:

  wordpress:
    image: dockerpress
    env_file: .env
    ports:
      - 80:80

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wordpress
